# fly.toml app configuration file generated for petadobt on 2023-05-31T04:45:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "petadobt"
primary_region = "sin"

[build]
  builder = "heroku/buildpacks:20"

[[services]]
  protocol = "tcp"
  internal_port = 8080
